version: "3.4"

volumes:
  caa-cache:

networks:
  production:
    external: true
  musicbrainz-docker_default:
    external: true

services:

  off-lb:
    build: .
    volumes:
      - caa-cache:/cache:z
    restart: unless-stopped 
    command: python off_lb.py
    expose:
      - 8000
    environment:
      - LETSENCRYPT_HOST=off.listenbrainz.org
      - LETSENCRYPT_EMAIL=rob@metabrainz.org
      - VIRTUAL_HOST=off.listenbrainz.org
    networks:
      - musicbrainz-docker_default
      - production
